In [1]:
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
import pandas as pd
import numpy as np
from datetime import datetime
import time

# 행 많이보기
pd.set_option('display.max_row', 500)
pd.set_option('display.max_columns', 100)

# 한글 폰트 설정
fm.get_fontconfig_fonts()

# fname 옵션을 사용하는 방법
font_location = 'C:\\WINDOWS\\Fonts\\\x7f\x7f\x7f\x7f.TTF' # For Windows
font_name = fm.FontProperties(fname=font_location).get_name()
plt.rc('font', family=font_name)
plt.rc('font', size=12)
plt.figure(figsize=(20,10))

# 지수 표현 안보기

In [2]:
name='2019+시청률(평균).xlsx'

In [3]:
data=pd.read_excel('./Data/2019+시청률(평균).xlsx')

In [4]:
data.drop('Unnamed: 0',axis=1,inplace=True)

In [5]:
data

,index,time,exposure_time,mcode,product_code,product_name,category,price,salesAMT,yy-mm-dd,s-hh-mm,f-hh-mm,year,month,date,hour,minute,dayofweek,tvrate,category_가구,category_가전,category_건강기능,category_농수축,category_생활용품,category_속옷,category_의류,category_이미용,category_잡화,category_주방,category_침구,dayofweek_0,dayofweek_1,dayofweek_2,dayofweek_3,dayofweek_4,dayofweek_5,dayofweek_6,kosdaq
0,0,2019-01-01 06:00:00,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900,2099000,2019-01-01,06:00,06:20,2019,1,1,6,0,1,0.000000,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,675.65
1,1,2019-01-01 06:00:00,20.0,100346,201079,테이트 여성 셀린니트3종,의류,39900,4371000,2019-01-01,06:00,06:20,2019,1,1,6,0,1,0.000000,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,675.65
2,2,2019-01-01 06:20:00,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900,3262000,2019-01-01,06:20,06:40,2019,1,1,6,20,1,0.000000,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,675.65
3,3,2019-01-01 06:20:00,20.0,100346,201079,테이트 여성 셀린니트3종,의류,39900,6955000,2019-01-01,06:20,06:40,2019,1,1,6,20,1,0.000000,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,675.65
4,4,2019-01-01 06:40:00,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900,6672000,2019-01-01,06:40,07:00,2019,1,1,6,40,1,0.000000,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,675.65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37367,38299,2019-12-31 23:40:00,20.0,100448,201391,일시불쿠첸압력밥솥 6인용,주방,148000,10157000,2019-12-31,23:40,24:00,2019,12,31,23,40,1,0.020762,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,669.83
37368,38300,2020-01-01 00:00:00,20.0,100448,201383,무이자쿠첸압력밥솥 10인용,주방,178000,50929000,2020-01-01,00:00,00:20,2020,1,1,0,0,2,0.026476,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,669.83
37369,38301,2020-01-01 00:00:00,20.0,100448,201390,일시불쿠첸압력밥솥 10인용,주방,168000,104392000,2020-01-01,00:00,00:20,2020,1,1,0,0,2,0.026476,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,669.83
37370,38302,2020-01-01 00:00:00,20.0,100448,201384,무이자쿠첸압력밥솥 6인용,주방,158000,13765000,2020-01-01,00:00,00:20,2020,1,1,0,0,2,0.026476,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,669.83
37371,38303,2020-01-01 00:00:00,20.0,100448,201391,일시불쿠첸압력밥솥 6인용,주방,148000,46608000,2020-01-01,00:00,00:20,2020,1,1,0,0,2,0.026476,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,669.83

          0                                                  1
0    100000         index                time  exposure_tim...
1    100001        index                time  exposure_time...
2    100002         index                time  exposure_tim...
3    100006         index                time  exposure_tim...
4    100009         index                time  exposure_tim...
..      ...                                                ...
682  100843         index                time  exposure_tim...
683  100844         index                time  exposure_tim...
684  100845         index                time  exposure_tim...
685  100846         index                time  exposure_tim...
686  100849         index                time  exposure_tim...

[687 rows x 2 columns]

In [38]:
mcode=data.iloc[0].loc['mcode']
sameidx=[]

In [42]:
i=0
while i<37372:
    if mcode==data.iloc[i].loc['mcode']:
        None
    else :
        sameidx.append(data.iloc[i].loc['index'])
        mcode=data.iloc[i].loc['mcode']
    i=i+1

In [48]:
# 한 방송은 일단 마더코드로 묶고, 
sameidx

[0,
 6,
 9,
 12,
 15,
 18,
 20,
 23,
 25,
 29,
 32,
 34,
 35,
 38,
 41,
 44,
 50,
 53,
 55,
 58,
 64,
 67,
 70,
 73,
 76,
 79,
 91,
 93,
 105,
 108,
 110,
 113,
 119,
 122,
 125,
 128,
 137,
 143,
 161,
 164,
 168,
 171,
 177,
 180,
 183,
 186,
 188,
 191,
 194,
 197,
 200,
 212,
 215,
 218,
 221,
 230,
 233,
 251,
 254,
 260,
 263,
 266,
 269,
 272,
 275,
 287,
 299,
 301,
 304,
 307,
 310,
 313,
 316,
 319,
 322,
 328,
 331,
 334,
 340,
 342,
 345,
 351,
 354,
 360,
 363,
 365,
 368,
 371,
 374,
 377,
 383,
 385,
 388,
 391,
 393,
 405,
 414,
 432,
 435,
 441,
 444,
 447,
 450,
 453,
 456,
 459,
 462,
 464,
 476,
 479,
 482,
 484,
 487,
 490,
 499,
 502,
 514,
 520,
 523,
 526,
 528,
 534,
 537,
 540,
 543,
 546,
 548,
 560,
 572,
 575,
 578,
 581,
 584,
 587,
 590,
 593,
 602,
 608,
 611,
 613,
 619,
 622,
 625,
 628,
 630,
 633,
 645,
 647,
 650,
 653,
 656,
 659,
 662,
 665,
 677,
 686,
 689,
 707,
 710,
 713,
 716,
 722,
 725,
 728,
 731,
 743,
 746,
 758,
 760,
 763,
 766,
 769,
 772,
 775,
 778,
 784,
 787,
 790,
 792,
 795,
 798,
 801,
 807,
 810,
 813,
 815,
 827,
 830,
 833,
 836,
 839,
 842,
 845,
 848,
 851,
 863,
 866,
 869,
 887,
 890,
 893,
 896,
 902,
 908,
 910,
 913,
 925,
 927,
 930,
 933,
 936,
 939,
 942,
 945,
 948,
 954,
 960,
 963,
 965,
 977,
 983,
 989,
 992,
 995,
 1001,
 1004,
 1006,
 1008,
 1020,
 1023,
 1035,
 1037,
 1040,
 1043,
 1045,
 1051,
 1060,
 1063,
 1081,
 1087,
 1090,
 1096,
 1102,
 1108,
 1110,
 1116,
 1119,
 1131,
 1134,
 1140,
 1142,
 1144,
 1147,
 1150,
 1162,
 1168,
 1177,
 1179,
 1182,
 1184,
 1196,
 1199,
 1202,
 1205,
 1208,
 1220,
 1223,
 1225,
 1228,
 1231,
 1234,
 1237,
 1240,
 1243,
 1255,
 1258,
 1260,
 1263,
 1269,
 1272,
 1275,
 1278,
 1281,
 1287,
 1290,
 1296,
 1308,
 1310,
 1313,
 1325,
 1328,
 1331,
 1334,
 1337,
 1340,
 1346,
 1352,
 1355,
 1373,
 1385,
 1388,
 1394,
 1397,
 1400,
 1403,
 1406,
 1418,
 1430,
 1433,
 1436,
 1439,
 1442,
 1445,
 1448,
 1451,
 1457,
 1463,
 1469,
 1475,
 1478,
 1484,
 1486,
 1492,
 1498,
 1501,
 1504,
 1510,
 1513,
 1516,
 1522,
 1524,
 1527,
 1530,
 1532,
 1535,
 1541,
 1544,
 1562,
 1564,
 1567,
 1570,
 1576,
 1579,
 1585,
 1588,
 1590,
 1593,
 1596,
 1599,
 1602,
 1605,
 1608,
 1611,
 1614,
 1620,
 1623,
 1629,
 1632,
 1638,
 1644,
 1647,
 1653,
 1659,
 1662,
 1664,
 1667,
 1670,
 1673,
 1685,
 1688,
 1706,
 1709,
 1712,
 1715,
 1717,
 1726,
 1744,
 1747,
 1750,
 1756,
 1762,
 1765,
 1767,
 1770,
 1776,
 1782,
 1785,
 1791,
 1803,
 1815,
 1821,
 1824,
 1827,
 1830,
 1833,
 1837,
 1849,
 1861,
 1879,
 1882,
 1885,
 1888,
 1891,
 1894,
 1897,
 1900,
 1902,
 1905,
 1908,
 1911,
 1914,
 1917,
 1920,
 1923,
 1926,
 1932,
 1935,
 1941,
 1959,
 1971,
 1974,
 1976,
 1979,
 1981,
 1984,
 1996,
 1999,
 2011,
 2014,
 2017,
 2020,
 2023,
 2026,
 2032,
 2035,
 2044,
 2062,
 2068,
 2080,
 2083,
 2085,
 2088,
 2091,
 2094,
 2096,
 2099,
 2102,
 2114,
 2117,
 2119,
 2122,
 2125,
 2128,
 2131,
 2134,
 2137,
 2140,
 2152,
 2164,
 2167,
 2173,
 2176,
 2179,
 2182,
 2185,
 2187,
 2190,
 2193,
 2199,
 2205,
 2208,
 2211,
 2214,
 2217,
 2220,
 2223,
 2241,
 2253,
 2256,
 2262,
 2265,
 2271,
 2277,
 2280,
 2284,
 2287,
 2290,
 2292,
 2298,
 2301,
 2307,
 2310,
 2312,
 2315,
 2319,
 2322,
 2334,
 2352,
 2355,
 2358,
 2361,
 2364,
 2370,
 2373,
 2376,
 2379,
 2381,
 2384,
 2387,
 2390,
 2393,
 2396,
 2399,
 2401,
 2404,
 2407,
 2410,
 2416,
 2419,
 2428,
 2434,
 2440,
 2443,
 2446,
 2449,
 2451,
 2454,
 2457,
 2460,
 2463,
 2466,
 2478,
 2481,
 2487,
 2490,
 2508,
 2514,
 2526,
 2529,
 2532,
 2535,
 2538,
 2541,
 2544,
 2550,
 2552,
 2555,
 2558,
 2561,
 2564,
 2567,
 2570,
 2573,
 2576,
 2579,
 2585,
 2588,
 2600,
 2603,
 2609,
 2615,
 2617,
 2620,
 2623,
 2625,
 2628,
 2631,
 2634,
 2637,
 2640,
 2643,
 2646,
 2649,
 2652,
 2655,
 2658,
 2661,
 2673,
 2679,
 2682,
 2685,
 2688,
 2691,
 2694,
 2697,
 2699,
 2702,
 2705,
 2717,
 2729,
 2732,
 2738,
 2741,
 2744,
 2756,
 2762,
 2768,
 2786,
 2798,
 2801,
 2804,
 2807,
 2810,
 2813,
 2815,
 2818,
 2821,
 2824,
 2830,
 2836,
 2839,
 2842,
 2846,
 2852,
 2855,
 2873,
 2879,
 2882,
 2888,
 2894,
 2897,
 2900,
 2903,
 2906,
 2909,
 2921,
 2923,
 2925,
 2928,
 2931,
 2934,
 2937,
 2940,
 2946,
 2952,
 2961,
 2964,
 2970,
 2976,
 2979,
 2982,
 2985,
 2988,
 3000,
 3006,
 3009,
 3012,
 3015,
 3018,
 3021,
 3023,
 3025,
 3034,
 3037,
 3049,
 3067,
 3073,
 3076,
 3082,
 3085,
 3087,
 3090,
 3093,
 3096,
 3099,
 3111,
 3117,
 3129,
 3132,
 3135,
 3141,
 3144,
 3150,
 3153,
 3171,
 3183,
 3186,
 3189,
 3192,
 3195,
 3198,
 3200,
 3203,
 3205,
 3208,
 3211,
 3214,
 3216,
 3219,
 3222,
 3225,
 3228,
 3231,
 3240,
 3252,
 3258,
 3261,
 3270,
 3273,
 3276,
 3279,
 3282,
 3285,
 3291,
 3293,
 3305,
 3311,
 3320,
 3326,
 3329,
 3333,
 3345,
 3363,
 3369,
 3372,
 3375,
 3381,
 3384,
 3387,
 3390,
 3396,
 3399,
 3402,
 3405,
 3408,
 3414,
 3417,
 3420,
 3423,
 3435,
 3447,
 3450,
 3456,
 3468,
 3486,
 3495,
 3501,
 3504,
 3510,
 3513,
 3516,
 3519,
 3531,
 3533,
 3535,
 3538,
 3544,
 3547,
 3550,
 3553,
 3556,
 3562,
 3565,
 3571,
 3583,
 3589,
 3592,
 3601,
 3604,
 3607,
 3613,
 3615,
 3618,
 3621,
 3624,
 3636,
 3639,
 3651,
 3654,
 3657,
 3660,
 3663,
 3681,
 3690,
 3696,
 3699,
 3705,
 3708,
 3711,
 3713,
 3716,
 3719,
 3722,
 3725,
 3737,
 3739,
 3742,
 3748,
 3751,
 3754,
 3756,
 3759,
 3765,
 3777,
 3795,
 3801,
 3804,
 3813,
 3816,
 3819,
 3825,
 3828,
 3840,
 3843,
 3855,
 3861,
 3864,
 3867,
 3870,
 3873,
 3876,
 3888,
 3890,
 3896,
 3902,
 3905,
 3908,
 3914,
 3917,
 3920,
 3923,
 3926,
 3928,
 3930,
 3933,
 3935,
 3938,
 3941,
 3944,
 3947,
 3950,
 3953,
 3956,
 3959,
 3965,
 3968,
 3971,
 3980,
 3983,
 3986,
 3989,
 3991,
 4003,
 4005,
 4011,
 4017,
 4020,
 4023,
 4026,
 4029,
 4032,
 4038,
 4041,
 4059,
 4062,
 4080,
 4083,
 4086,
 4089,
 4095,
 4097,
 4100,
 4112,
 4114,
 4126,
 4129,
 4132,
 4135,
 4138,
 4141,
 4144,
 4162,
 4165,
 4171,
 4174,
 4177,
 4186,
 4189,
 4192,
 4195,
 4198,
 4201,
 4213,
 4215,
 4217,
 4220,
 4223,
 4235,
 4238,
 4241,
 4244,
 4247,
 4250,
 4256,
 4274,
 4277,
 4280,
 4289,
 4295,
 4298,
 4301,
 4304,
 4316,
 4319,
 4321,
 4323,
 4326,
 4329,
 4332,
 4335,
 4338,
 4347,
 4359,
 4377,
 4389,
 4398,
 4404,
 4407,
 4410,
 4416,
 4419,
 4422,
 4434,
 4437,
 4440,
 4443,
 4446,
 4449,
 4452,
 4455,
 4457,
 4460,
 4469,
 4487,
 4493,
 4496,
 4498,
 4507,
 4513,
 4516,
 4519,
 4522,
 4525,
 4528,
 4531,
 4543,
 4546,
 4552,
 4555,
 4558,
 4561,
 4567,
 4576,
 4582,
 4594,
 4603,
 4606,
 4612,
 4615,
 4618,
 4621,
 4624,
 4627,
 4630,
 4642,
 4645,
 4648,
 4651,
 4654,
 4657,
 4660,
 4669,
 4672,
 4684,
 4690,
 4708,
 4720,
 4726,
 4729,
 4732,
 4734,
 4736,
 4748,
 4751,
 4754,
 4757,
 4761,
 4764,
 4767,
 4770,
 4782,
 4785,
 4794,
 4800,
 4818,
 4821,
 4824,
 4833,
 4839,
 4842,
 ...]

In [49]:
#i이상 j미만
# j-1의 값의 f-hh-mm값을 구한다
broad_df=pd.DataFrame()

In [52]:
for i in range(len(sameidx)):
    j=i+1
    if i

7182